services:
  app:
    container_name: honeytrap
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/workspace/app
      - ./data:/workspace/data
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: unless-stopped